version: '3.4'

services:
  app-dev:
    container_name: trmm-app-dev
    image: node:16-alpine
    restart: always
    command: /bin/sh -c "npm install --cache ~/.npm && npm run serve"
    user: 1000:1000
    working_dir: /workspace/web
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:443"
    networks:
      dev:
        aliases:
          - tactical-frontend

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK}
